[package]
name = "lynch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.38.0"
glam = "0.27.0"
lazy_static = "1.4.0"
winapi = {version="0.3.9",features = ["profileapi"] }
